=== sagarpoudel638/MotorShopManagement/catalog_18030043.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<!-- defining element so that it is easy to refer later on -->
  <xs:element name="name_of_shop" type="xs:string"/>
  <xs:element name="address" type="xs:string"/>
  <xs:element name="phone_no" type="xs:long"/>
  <xs:element name="URL" type="xs:anyURI"/>
  <xs:element name="logo" type="xs:string"/>
  <xs:element name="length" type="xs:string"/>
  <xs:element name="width" type="xs:string"/>
  <xs:element name="height" type="xs:string"/>
  <xs:element name="brand_name" type="xs:string"/>
  <xs:element name="item_no" type="xs:short"/>
  <xs:element name="description" type="xs:string"/>
  <xs:element name="quantity" type="xs:float"/>
  <xs:element name="price" type="xs:int"/>
 <!-- -->
<!-- complex type element manufacturer--> 
  <xs:element name="manufacturer">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute type="xs:byte" name="manufacturer_id" use="optional"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
<!-- complex type element color--> 
  <xs:element name="color">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute type="xs:string" name="color_family" use="optional"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
 <!-- complex type element fuel_type-->  
  <xs:element name="fuel_type">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute type="xs:byte" name="fuel_id" use="optional"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
<!-- complex type element dimension--> 
  <xs:element name="dimension">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="length"/>
        <xs:element ref="width"/>
        <xs:element ref="height"/>
      </xs:sequence>
    </xs:complexType>	
  </xs:element>
<!-- Defining optional fields-->   
  <xs:element name="roof" type="xs:string"/>
  <xs:element name="camera" type="xs:string"/>
  <xs:element name="negotiation" type="xs:string"/>
  <xs:element name="entertainment" type="xs:string"/>
  <xs:element name="parking" type="xs:string"/>
 <!-- complex type element hatchback--> 
  <xs:element name="hatchback">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="brand_name"/>
        <xs:element ref="item_no"/>
        <xs:element ref="description"/>
        <xs:element ref="quantity"/>
        <xs:element ref="price"/>
        <xs:element ref="manufacturer"/>
        <xs:element ref="color"/>
        <xs:element ref="fuel_type"/>
        <xs:element ref="dimension"/>
        <xs:element ref="roof" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute type="xs:byte" name="id" use="optional"/>
      <xs:attribute type="xs:byte" name="type_id" use="optional"/>
    </xs:complexType>
  </xs:element>
 <!-- complex type element sedan-->  
  <xs:element name="sedan">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="brand_name"/>
        <xs:element ref="item_no"/>
        <xs:element ref="description"/>
        <xs:element ref="quantity"/>
        <xs:element ref="price"/>
        <xs:element ref="manufacturer"/>
        <xs:element ref="color"/>
        <xs:element ref="fuel_type"/>
        <xs:element ref="dimension"/>
        <xs:element ref="camera" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute type="xs:byte" name="id" use="optional"/>
      <xs:attribute type="xs:byte" name="type_id" use="optional"/>
    </xs:complexType>
  </xs:element>
<!-- complex type element SUV--> 
  <xs:element name="SUV">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="brand_name"/>
        <xs:element ref="item_no"/>
        <xs:element ref="description"/>
        <xs:element ref="quantity"/>
        <xs:element ref="price"/>
        <xs:element ref="manufacturer"/>
        <xs:element ref="color"/>
        <xs:element ref="fuel_type"/>
        <xs:element ref="dimension"/>
        <xs:element ref="negotiation" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute type="xs:byte" name="id" use="optional"/>
      <xs:attribute type="xs:byte" name="type_id" use="optional"/>
    </xs:complexType>
  </xs:element>
<!-- complex type element van--> 
  <xs:element name="van">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="brand_name"/>
        <xs:element ref="item_no"/>
        <xs:element ref="description"/>
        <xs:element ref="quantity"/>
        <xs:element ref="price"/>
        <xs:element ref="manufacturer"/>
        <xs:element ref="color"/>
        <xs:element ref="fuel_type"/>
        <xs:element ref="dimension"/>
      </xs:sequence>
      <xs:attribute type="xs:byte" name="id" use="optional"/>
      <xs:attribute type="xs:byte" name="type_id" use="optional"/>
    </xs:complexType>
  </xs:element>
  <!-- complex type element pickup--> 
  <xs:element name="pickup">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="brand_name"/>
        <xs:element ref="item_no"/>
        <xs:element ref="description"/>
        <xs:element ref="quantity"/>
        <xs:element ref="price"/>
        <xs:element ref="manufacturer"/>
        <xs:element ref="color"/>
        <xs:element ref="fuel_type"/>
        <xs:element ref="dimension"/>
        <xs:element ref="entertainment" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute type="xs:byte" name="id" use="optional"/>
      <xs:attribute type="xs:byte" name="type_id" use="optional"/>
    </xs:complexType>
  </xs:element>
<!-- complex type element roadster-->   
  <xs:element name="roadster">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="brand_name"/>
        <xs:element ref="item_no"/>
        <xs:element ref="description"/>
        <xs:element ref="quantity"/>
        <xs:element ref="price"/>
        <xs:element ref="manufacturer"/>
        <xs:element ref="color"/>
        <xs:element ref="fuel_type"/>
        <xs:element ref="dimension"/>
        <xs:element ref="parking" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute type="xs:byte" name="id"/>
      <xs:attribute type="xs:byte" name="type_id"/>
    </xs:complexType>
  </xs:element>
<!-- complex type element shop_info-->   
  <xs:element name="shop_info">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name_of_shop"/>
        <xs:element ref="address"/>
        <xs:element ref="phone_no"/>
        <xs:element ref="URL"/>
        <xs:element ref="logo"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
<!-- complex type element shop_items--> 
  <xs:element name="shop_items">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="hatchback" maxOccurs="unbounded" minOccurs="0"/>
        <xs:element ref="sedan" maxOccurs="unbounded" minOccurs="0"/>
        <xs:element ref="SUV" maxOccurs="unbounded" minOccurs="0"/>
        <xs:element ref="van" maxOccurs="unbounded" minOccurs="0"/>
        <xs:element ref="pickup" maxOccurs="unbounded" minOccurs="0"/>
        <xs:element ref="roadster"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
<!-- complex type element shop-->   
  <xs:element name="shop">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="shop_info"/>
        <xs:element ref="shop_items"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== sagarpoudel638/MotorShopManagement/catalog_18030043.xml
<?xml version="1.0" encoding="UTF-8"?>   
<?xml-stylesheet type="text/css" href="catalog_18030043.css"?>
<shop xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
 		xsi:noNamespaceSchemaLocation="catalog_18030043.xsd">
		
		
	<shop_info>
	
		<name_of_shop>Dhurbatara Motor Sales</name_of_shop>	
		<address>Nepalgunj-12,Banke,Nepal</address>
		<phone_no>9868299552</phone_no>
		<URL>www.dhurbataramotors.com</URL>
		<logo></logo> 
		
	</shop_info>
	
	
	<shop_items>
	
		<hatchback id="01" type_id="001">
		
		
			
			<brand_name>Maruti Suzuki Swift </brand_name>
			<item_no>0458</item_no>
			<description>
			
				<![CDATA[  
					The Swift was the game changer in our thriving car market back then. 
					It looked quirky and showed us that a hatchback can be practical and fun at the same time. 
					It also won the coveted Indian Car of the Year Award (ICOTY) in 2012.
				]]>
				
			</description>
			<quantity>2</quantity>
			<price>1500000</price>
			<manufacturer manufacturer_id="1">Maruti Suzuki</manufacturer>
			<color color_family="red">Solid Fire Red </color>
			<fuel_type fuel_id="1">Petrol</fuel_type>
			<dimension>
			
				<length>3850mm</length>
				<width>1695mm</width>
				<height>1530mm</height>
				
			</dimension>
			
		</hatchback>	
		<hatchback id="02" type_id="001">
			
			<brand_name>TATA Altroz</brand_name>
			<item_no >0459</item_no>
			<description>
				<![CDATA[
					The Altroz is Tata’s latest, most modern, and its most futuristic looking car.
					the Altroz stands out with the quirky black-finished sills running below the windows called the ‘shooting star beltline’, 
					and the hidden rear door handle. Also prominent are the well-defined front wheel arches and sharp shoulder creases running across the sides. 
					At the back, the sharply raked and contoured tailgate has integrated wrap-around LED taillamps.			
				]]> 
			</description>
			<quantity>1</quantity>
			<price>1800000</price>
			<manufacturer manufacturer_id="2">TATA</manufacturer>
			<color color_family="red">Downtown Red</color>
			<fuel_type fuel_id="2">Diesel</fuel_type>
			<dimension>
				<length>3990mm</length>
				<width>1755mm</width>
				<height>1523mm</height>
			</dimension>
			
		</hatchback>
		<hatchback id="03" type_id="001" >
			
			<brand_name>Hyundai Grand i10</brand_name>
			<item_no>0461</item_no>
			<description>
				<![CDATA[
					Hyundai Grand i10 is a 5 seater hatchback. It is available in 2 variants, a 1197 cc, BS6 and a single Manual transmission. 
					Other key specifications of the Grand i10 include a ground clearance of 165mm and boot space of 256 Liters. 
					The Grand i10 is available in 4 colours. 
					Over 1269 User reviews basis Mileage, Performance, Price and overall experience of users for Hyundai Grand i10.
				]]>
			</description>
			<quantity>2</quantity>
			<price>1200000</price>
			<manufacturer manufacturer_id="3">Hyundai</manufacturer>
			<color color_family="blue">Marina Blue</color>
			<fuel_type fuel_id="1">Petrol</fuel_type>
			<dimension>
				<length>3765mm</length>
				<width>1660mm</width>
				<height>1520mm</height>
			</dimension>
			<roof>Roof rack Available</roof>
			
			
		</hatchback>
		
		
		<sedan id="04" type_id="002" >
		
		
			
			<brand_name>Nissan Leaf</brand_name>
			<item_no >0462</item_no>
			<description>
				<![CDATA[
					That original Leaf has amazingly loyal and satisfied customers. 
					They loved the tiny running costs, convenience of home charging, silence, and simple practicality. 
					And they liked that at the top and bottom it was just a car - five seats, good boot, easy to drive, affordable to buy. 
					People who have owned electric cars almost never return to combustion.
				]]>
			</description> 
			<quantity> 1</quantity>
			<price>3000000</price>
			<manufacturer manufacturer_id="4">Nissan</manufacturer>
			<color color_family="white">Pearl White</color>
			<fuel_type fuel_id="3">Electric</fuel_type>
			<dimension>
				<length>4490mm</length>
				<width>2030mm</width>
				<height>1530mm</height>
			</dimension>
			<camera>  360 degree view camera</camera>
			
		</sedan>
		<sedan id="05" type_id="002">
			<brand_name>Verna</brand_name>
			<item_no >0463</item_no>
			<description>
				<![CDATA[
					Hyundai Verna is a 5 seater. It is available in 11 variants, 3 engine options that are BS6 compliant and 2 transmission options: 
					Manual and Automatic. Other key specifications of the Verna include a boot space of 480 Liters. 
					The Verna is available in 6 colours. 
					Over 75 User reviews basis Mileage, Performance, Price and overall experience of users for Hyundai Verna.
				]]>
			</description>
			<quantity>2</quantity>
			<price>2000000</price>
			<manufacturer manufacturer_id="3">Hyundai</manufacturer>
			<color color_family="black">Phantom Black</color>
			<fuel_type fuel_id="2">Diesel</fuel_type>
			<dimension>
				<length>4440mm</length>
				<width>1729mm</width>
				<height>1475mm</height>
			</dimension>
		</sedan>	
		<sedan  id="06" type_id="002">
			
			<brand_name>Skoda Rapid</brand_name>
			<item_no>0464</item_no>
			<description>
				<![CDATA[
					Skoda Rapid is a 5 seater sedan . It is available in 5 variants, a 999 cc, 
					BS6 and a single Manual transmission. Other key specifications of the Rapid include a kerb weight of 1111kg, ground clearance of 163mm and boot space of 460 Liters.
					The Rapid is available in 4 colours. 
					Over 245 User reviews basis Mileage, Performance, Price and overall experience of users for Skoda Rapid.
				]]> 
			</description>
			<quantity>1</quantity>
			<price>1800000</price>
			<manufacturer manufacturer_id="5">Skoda</manufacturer>
			<color color_family="silver">Brilliant Silver</color>
			<fuel_type fuel_id="1">Petrol</fuel_type>
			<dimension>
				<length>4413mm</length>
				<width>1699mm</width>
				<height>1466mm</height>
			</dimension>
			
			
		</sedan>
		
		
		
		<SUV id="07" type_id="003">
		
		
			
			<brand_name>TATA Nexon EV</brand_name>
			<item_no >0465</item_no>
			<description>
				<![CDATA[
					Tata Nexon EV Range, Electric Motor and Battery: 
					The Nexon EV uses Tata's Ziptron EV powertrain technology that features a 30.2kWh lithium-ion battery with a claimed range of 312km. 
					It gets an 8-year standard warranty and an IP67 waterproof battery pack.
				]]> 
			</description>
			<quantity>1</quantity>
			<price>3000000</price>
			<manufacturer manufacturer_id="2">TATA</manufacturer>
			<color color_family="white">Glacier White</color>
			<fuel_type fuel_id="3">Electric</fuel_type>
			<dimension>
				<length>3993mm</length>
				<width>1811mm</width>
				<height>1606mm</height>
			</dimension>
		</SUV>	
		<SUV  id="08" type_id="003">	
			
			<brand_name>Mahindra Scorpio</brand_name>
			<item_no >0466</item_no>
			<description>
				<![CDATA[
					Mahindra Scorpio is a 7 seater suv 
					Other key specifications of the Scorpio include a ground clearance of 180mm and boot space of 460 Liters. 
					Over 1527 User reviews basis Mileage, Performance, Price and overall experience of users for Mahindra Scorpio.
				]]> 
			</description>
			<quantity>1</quantity>
			<price>2300000</price>
			<manufacturer manufacturer_id="6">Mahindra</manufacturer>
			<color color_family="red">Molten Red</color>
			<fuel_type fuel_id="2">Diesel</fuel_type>
			<dimension>
				<length>4456mm</length>
				<width>1820mm</width>
				<height>1995mm</height>
			</dimension>
			<negotiation>Available</negotiation>
		</SUV>
		<SUV id="09" type_id="003">
			
			
			<brand_name>Kia Seltos</brand_name>
			<item_no>0467</item_no>
			<description>
				<![CDATA[
					Kia Seltos is a 5 seater suv .  Other key specifications of the Seltos include a boot space of 433 Liters. 
					Over 2112 User reviews basis Mileage, Performance, Price and overall experience of users for Kia Seltos.
				]]> 
			</description>
			<quantity>1</quantity>
			<price>2500000</price>
			<manufacturer manufacturer_id ="7">KIA</manufacturer>
			<color color_family="black">Aurora Black Pearl</color>
			<fuel_type fuel_id="1">Petrol</fuel_type> 
			<dimension>
				<length>4315mm</length>
				<width>1800mm</width>
				<height>1645mm</height>
			</dimension>
			
			
		</SUV>
		
		
		
		<van id ="10" type_id="004">
		
		
			
			<brand_name>eSupro Cargo Van</brand_name>
			<item_no >0468</item_no>
			<description>
				<![CDATA[
					Mahindra brings you eSupro, a stylish , 
					spacious van which is a whole new concept in cargo transportation and people movement. 
					It is an advanced electric van that brings emissions down to zero, absolute zero.
					The eSupro van with zero emission has many advantages. 
				]]> 
			</description>
			<quantity>1</quantity>
			<price>800000</price>
			<manufacturer manufacturer_id="6">Mahindra</manufacturer>
			<color color_family="blue">Deep Warm Blue</color>
			<fuel_type fuel_id="3">Electric</fuel_type>
			<dimension>
				<length>3798mm</length>
				<width>1540mm</width>
				<height>1922mm</height>
			</dimension>
		</van>
		<van  id ="11" type_id="004">
			
			<brand_name>TATA Magic</brand_name>
			<item_no>0469</item_no>
			<description>
				<![CDATA[	
					Tata Magic Diesel is a commercial vehicle by Tata Motors in the MUV segment. 
					Magic comes with a 4 stroke 702cc engine giving a performance of 16 BHP @ 3200 rpm and 38 Nm @ 2000 rpm.
					At a price point of around 4.50 lakhs, Tata Magic has competition from Mahindra Maxximo which gives the same performance at a price point of 3.05 lakhs. 
					TATA Magic has an impressive mileage of 17.9 kmpl.
				]]> 
			</description>
			<quantity>3</quantity>
			<price>1200000</price>
			<manufacturer manufacturer_id="2">TATA</manufacturer>
			<color color_family="silver">silver</color>
			<fuel_type fuel_id="1">Petrol</fuel_type>
			<dimension>
				<length>3790mm</length>
				<width>1500mm</width>
				<height>1845mm</height>
			</dimension>
			
		</van>
		<van id ="12" type_id="004">
			
			<brand_name>EECO</brand_name>
